version: "3.9"
services:
  app:
    build: .
    image: jameer:hackernews
    environment:
      - REDIS_HOST=redis
    ports:
      - "8081:8081"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"